### ISSUE TITLE
deployed to Kubernetes, uwsgi doesn't respond, flask does

### ISSUE THREAD

**Issue by stenwt** [rchakode/kube-opex-analytics#33]
Continuing from #30 : 

we're seeing the same thing in a Kubernetes 1.15 cluster deployed with RKE. 

This deployment works: 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-opex
  name: kube-opex
  namespace: kube-opex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-opex
  template:
    metadata:
      labels:
        app: kube-opex
    spec:
      containers:
      - env:
        - name: KOA_BILLING_CURRENCY_SYMBOL
          value: $
        - name: KOA_COST_MODEL
          value: RATIO
        - name: KOA_DB_LOCATION
          value: /data/db
        - name: KOA_ENABLE_PROMETHEUS_EXPORTER
          value: "false"
        - name: KOA_K8S_API_ENDPOINT
          value: https://kubernetes.default
        - name: KOA_K8S_API_VERIFY_SSL
          value: "false"
        image: rchakode/kube-opex-analytics
        imagePullPolicy: Always
        name: kube-opex
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: 700m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 830405
        volumeMounts:
        - mountPath: /data
          name: kube-opex
      volumes:
      - name: kube-opex
        persistentVolumeClaim:
          claimName: kube-opex
      securityContext: {}
      serviceAccount: kube-opex
      serviceAccountName: kube-opex
```
but if I set KOA_ENABLE_PROMETHEUS_EXPORTER in that deployment to "true", the uwsgi server never responds. If I look at the process table, or install the iproute2 package and run "ss," I can see the process is up and listening on all interfaces: 

```
# ss -tln
State                 Recv-Q                 Send-Q                                   Local Address:Port                                   Peer Address:Port
LISTEN                4                      100                                            0.0.0.0:5483                                        0.0.0.0:*
```
But uwsgi never returns a response, and doesn't log anything, it just hangs until the client times out the connection.
