### ISSUE TITLE
Error displaying hourly, daily charts

### ISSUE THREAD

**Issue by jaredstehler** [rchakode/kube-opex-analytics#46]
The hourly 7d and daily 14d cumulative charts are not displaying. There is an error in the javascript console: 
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at drawStackedBar (stacked-bar.js:574)
    at HTMLDivElement.<anonymous> (stacked-bar.js:177)
    at R.each (d3-selection.min.js:2)
    at exports (stacked-bar.js:165)
    at R.call (d3-selection.min.js:2)
    at updateStackedBarChart (frontend.js:242)
    at Object.success (frontend.js:636)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at x (jquery-1.11.0.min.js:4)
```

and an error in the server:
```
2020-12-01 12:31:02,437 - kube-opex-analytics - ERROR - KeyError Exception in dump_analytics ('cpu')
ERROR:kube-opex-analytics:KeyError Exception in dump_analytics ('cpu')
WARNING:waitress.queue:Task queue depth is 1
```

Config info:
```
      - env:
        - name: KOA_BILLING_CURRENCY_SYMBOL
          value: $
        - name: KOA_BILLING_HOURLY_RATE
          value: "0"
        - name: KOA_COST_MODEL
          value: CUMULATIVE_RATIO
        - name: KOA_DB_LOCATION
          value: /data/db
        - name: KOA_K8S_API_ENDPOINT
          value: https://kubernetes.default
        - name: KOA_K8S_API_VERIFY_SSL
          value: "false"
```

image: rchakode/kube-opex-analytics:20.10.4
kube version: v1.18.10
